name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "thank you for opening a new issue, that's really help me to improve this project. and your feedback is very usefull!"
        pr-message: "Thank you for creating a new pull requests. your contributions is really helping this project to improve!!"
